### ISSUE TITLE
build without git repo

### ISSUE THREAD

**Issue by jschueller** [SALib/SALib#111]
it seems salib does not build outside of git
we'd like to build from the tarball for integration in anaconda, is it possible ?
https://github.com/conda-forge/staged-recipes/pull/1753

**Comment by jdherman** [comment]
@jschueller this would be awesome, but I don't have much experience with building anaconda packages so I'm not sure how to fix it. Should we include your workaround from the link? 

Why does it need git to build, won't `python setup.py install` work? Maybe git is being used for the automated version numbering, not sure. @willu47 may know more about this. 

Anyway we would be happy to figure this out, just need some more information about what's missing.

**Comment by jschueller** [comment]
yes it's for getting the version:
```
+ python setup.py install --single-version-externally-managed --record=record.txt
ERROR:root:Error parsing
Traceback (most recent call last):
  File "/home/xantares/miniconda2/conda-bld/salib_1478284778199/_b_env_placehold_placeho/lib/python2.7/site-packages/pyscaffold/contrib/pbr/pbr/core.py", line 111, in pbr
    attrs = util.cfg_to_args(path, dist.script_args)
  File "/home/xantares/miniconda2/conda-bld/salib_1478284778199/_b_env_placehold_placeho/lib/python2.7/site-packages/pyscaffold/contrib/pbr/pbr/util.py", line 246, in cfg_to_args
    pbr.hooks.setup_hook(config)
  File "/home/xantares/miniconda2/conda-bld/salib_1478284778199/_b_env_placehold_placeho/lib/python2.7/site-packages/pyscaffold/contrib/pbr/pbr/hooks/__init__.py", line 25, in setup_hook
    metadata_config.run()
  File "/home/xantares/miniconda2/conda-bld/salib_1478284778199/_b_env_placehold_placeho/lib/python2.7/site-packages/pyscaffold/contrib/pbr/pbr/hooks/base.py", line 27, in run
    self.hook()
  File "/home/xantares/miniconda2/conda-bld/salib_1478284778199/_b_env_placehold_placeho/lib/python2.7/site-packages/pyscaffold/contrib/pbr/pbr/hooks/metadata.py", line 26, in hook
    self.config['name'], self.config.get('version', None))
  File "/home/xantares/miniconda2/conda-bld/salib_1478284778199/_b_env_placehold_placeho/lib/python2.7/site-packages/pyscaffold/contrib/pbr/pbr/packaging.py", line 710, in get_version
    raise Exception("Versioning for this project requires either an sdist"
Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. Are you sure that git is installed?
error in setup command: Error parsing /home/xantares/miniconda2/conda-bld/salib_1478284778199/work/SALib-1.0.1/setup.cfg: Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. Are you sure that git is installed?
Command failed: /bin/bash -x -e /home/xantares/miniconda2/conda-bld/salib_1478284778199/work/SALib-1.0.1/conda_build.sh
```

**Comment by willu47** [comment]
PyScaffold, used for packaging SALib uses [pbr](http://docs.openstack.org/developer/pbr/packagers.html) which has some flags you can set when building distributions. This may solve the versioning issues, by skipping references to git.

**Comment by jschueller** [comment]
It seems these vars are ignored ; setting PBR_VERSION and/or SKIP_GIT_SDIST env variables has no effect.

**Comment by willu47** [comment]
This is similar to [this pbr bug](https://bugs.launchpad.net/pbr/+bug/1379579). There are a few solutions mentioned in the comments, the simplest seems to be to upgrade setup tools to 0.7.0 and above.

**Comment by jschueller** [comment]
that's not it, setuptools is up to date

**Comment by willu47** [comment]
Hi @jschueller, I see over on the conda repo that you managed to find a work-around. 

I found that running `export SKIP_GIT_SDIST=1` did indeed skip the git context when building an sdist (`python setup.py sdist`).


Before setting SKIP_GIT_SDIST
```bash
$ python setup.py sdist
running sdist
running egg_info
writing dependency_links to SALib.egg-info/dependency_links.txt
writing top-level names to SALib.egg-info/top_level.txt
writing SALib.egg-info/PKG-INFO
writing requirements to SALib.egg-info/requires.txt
[pbr] Processing SOURCES.txt
[pbr] In git context, generating filelist from git     <<< This line disappeared
warning: no files found matching 'AUTHORS'
warning: no files found matching 'ChangeLog'
warning: no previously-included files found matching '.gitreview'
warning: no previously-included files matching '*.pyc' found anywhere in distribution
writing manifest file 'SALib.egg-info/SOURCES.txt'
```

After setting SKIP_GIT_SDIST
```bash
$ python setup.py sdist
running sdist
running egg_info
writing SALib.egg-info/PKG-INFO
writing dependency_links to SALib.egg-info/dependency_links.txt
writing requirements to SALib.egg-info/requires.txt
writing top-level names to SALib.egg-info/top_level.txt
[pbr] Processing SOURCES.txt
reading manifest file 'SALib.egg-info/SOURCES.txt'     <<< File list read from manifest
warning: no files found matching 'AUTHORS'
warning: no files found matching 'ChangeLog'
warning: no previously-included files found matching '.gitignore'
warning: no previously-included files found matching '.gitreview'
warning: no previously-included files matching '*.pyc' found anywhere in distribution
writing manifest file 'SALib.egg-info/SOURCES.txt'
```

**Comment by jschueller** [comment]
noted, thanks a bunch

**Comment by jschueller** [comment]
this doesnt work when installing (python setup.py install)

**Comment by jschueller** [comment]
my work-around is not optimal as ```salib.__version__``` report 0.0

**Comment by willu47** [comment]
Version 3.0 (forthcoming) of Pyscaffold drops the requirement for pbr, so hopefully that will fix this bug...

**Comment by willu47** [comment]
@jschueller - we have updated SALib to use the most recent version of PyScaffold which does away with the requirement for pbr.
