### ISSUE TITLE
[JOSS review] failed run of the tests after fresh installation

### ISSUE THREAD

**Issue by stijnvanhoey** [SALib/SALib#117]
[JOSS review](https://github.com/openjournals/joss-reviews/issues/97)

When doing a fresh install of SALib in a conda py35 environment:

```
- blas=1.1=openblas
- cairo=1.14.6=0
- certifi=2016.9.26=py35_0
- cycler=0.10.0=py35_0
- fontconfig=2.11.1=5
- freetype=2.6.3=1
- gettext=0.19.7=1
- glib=2.51.0=2
- harfbuzz=1.0.6=3
- icu=56.1=4
- jpeg=9b=0
- libffi=3.2.1=2
- libgfortran=3.0.0=1
- libiconv=1.14=4
- libpng=1.6.26=0
- libtiff=4.0.6=7
- libxml2=2.9.4=3
- matplotlib=1.5.3=np111py35_3
- ncurses=5.9=10
- numpy=1.11.2=py35_blas_openblas_202
- openblas=0.2.19=0
- openssl=1.0.2j=0
- pango=1.40.3=0
- pcre=8.39=1
- pip=9.0.1=py35_1
- pixman=0.34.0=0
- pyparsing=2.1.10=py35_0
- pyqt=4.11.4=py35_4
- python=3.5.2=2
- python-dateutil=2.6.0=py35_0
- pytz=2016.10=py35_0
- qt=4.8.7=3
- readline=6.2=2
- scipy=0.18.1=np111py35_blas_openblas_201
- setuptools=29.0.1=py35_1
- sip=4.18=py35_0
- six=1.10.0=py35_1
- sqlite=3.13.0=1
- tk=8.5.19=1
- wheel=0.29.0=py35_0
- xz=5.2.2=0
- zlib=1.2.8=3
- pip:
  - salib==1.0.1
```

and running the test-functions `python setup.py test`

I get the following error report (showing the last section with the errors:
```
...
======================================================================
FAIL: SALib.tests.test_plotting.test_morris_covariance_plot.test
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/stijn_vanhoey/githubs/forks/SALib/.eggs/nose-1.3.7-py3.5.egg/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/stijn_vanhoey/miniconda2/envs/salib/lib/python3.5/site-packages/matplotlib/testing/decorators.py", line 53, in failer
    result = f(*args, **kwargs)
  File "/home/stijn_vanhoey/miniconda2/envs/salib/lib/python3.5/site-packages/matplotlib/testing/decorators.py", line 220, in do_test
    '(RMS %(rms).3f)'%err)
matplotlib.testing.exceptions.ImageComparisonFailure: images not close: /home/stijn_vanhoey/githubs/forks/SALib/result_images/test_plotting/covariance_plot.png vs. /home/stijn_vanhoey/githubs/forks/SALib/result_images/test_plotting/covariance_plot-expected.png (RMS 16.765)

======================================================================
FAIL: SALib.tests.test_plotting.test_morris_covariance_plot_grouped.test
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/stijn_vanhoey/githubs/forks/SALib/.eggs/nose-1.3.7-py3.5.egg/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/stijn_vanhoey/miniconda2/envs/salib/lib/python3.5/site-packages/matplotlib/testing/decorators.py", line 53, in failer
    result = f(*args, **kwargs)
  File "/home/stijn_vanhoey/miniconda2/envs/salib/lib/python3.5/site-packages/matplotlib/testing/decorators.py", line 220, in do_test
    '(RMS %(rms).3f)'%err)
matplotlib.testing.exceptions.ImageComparisonFailure: images not close: /home/stijn_vanhoey/githubs/forks/SALib/result_images/test_plotting/covariance_plot_grouped.png vs. /home/stijn_vanhoey/githubs/forks/SALib/result_images/test_plotting/covariance_plot_grouped-expected.png (RMS 15.536)

----------------------------------------------------------------------
Ran 95 tests in 14.192s

FAILED (SKIP=6, failures=2)
```

**Comment by willu47** [comment]
This is a bit of a frustrating test failure!  The tests in question compare the plots made by the plotting module to a test fixture in the fixture folder. If the backend for a matplotlib is different to that used to produce the fixture, then the plot generated during the test may look rather different, but still be perfectly reasonable (just a different format).  I doubt this has anything to do with python 3.5, but rather the install or configuration of matplotlib.

**Comment by stijnvanhoey** [comment]
Dear willu47, I do understand the frustration here. What I propose is that you provide me with an export from pyenv or a conda environment (`conda env export > environment.yml`) in order to reproduce your environment and rerun the tests.

**Comment by willu47** [comment]
Okay, will do.  Otherwise, the tests are succeeding on the [Travis CI server](https://travis-ci.org/SALib/SALib).

Here's my `environment.yml`:

```yaml
name: salib
channels: !!python/tuple
- defaults
dependencies:
- alabaster=0.7.9=py35_0
- babel=2.3.4=py35_0
- cycler=0.10.0=py35_0
- docutils=0.12=py35_2
- freetype=2.5.5=1
- icu=54.1=0
- imagesize=0.7.1=py35_0
- jinja2=2.8=py35_1
- libpng=1.6.22=0
- markupsafe=0.23=py35_2
- matplotlib=1.5.3=np111py35_1
- mkl=11.3.3=0
- numpy=1.11.2=py35_0
- openssl=1.0.2j=0
- pip=9.0.1=py35_1
- pygments=2.1.3=py35_0
- pyparsing=2.1.4=py35_0
- pyqt=5.6.0=py35_1
- python=3.5.2=0
- python-dateutil=2.6.0=py35_0
- pytz=2016.10=py35_0
- qt=5.6.2=0
- readline=6.2=2
- requests=2.12.3=py35_0
- scipy=0.18.1=np111py35_0
- setuptools=27.2.0=py35_0
- sip=4.18=py35_0
- six=1.10.0=py35_0
- snowballstemmer=1.2.1=py35_0
- sphinx=1.5=py35_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- wheel=0.29.0=py35_0
- xz=5.2.2=0
- zlib=1.2.8=3
- pip:
  - commonmark==0.5.4
  - recommonmark==0.4.0
prefix: /Users/will2/miniconda3/envs/salib
```

**Comment by stijnvanhoey** [comment]
I reran the test functions with the new environment, having the same failures:

```
...
======================================================================
FAIL: SALib.tests.test_plotting.test_morris_covariance_plot.test
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/stijn_vanhoey/githubs/forks/SALib/.eggs/nose-1.3.7-py3.5.egg/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/stijn_vanhoey/miniconda2/envs/salibwill/lib/python3.5/site-packages/matplotlib/testing/decorators.py", line 53, in failer
    result = f(*args, **kwargs)
  File "/home/stijn_vanhoey/miniconda2/envs/salibwill/lib/python3.5/site-packages/matplotlib/testing/decorators.py", line 220, in do_test
    '(RMS %(rms).3f)'%err)
matplotlib.testing.exceptions.ImageComparisonFailure: images not close: /home/stijn_vanhoey/githubs/forks/SALib/result_images/test_plotting/covariance_plot.png vs. /home/stijn_vanhoey/githubs/forks/SALib/result_images/test_plotting/covariance_plot-expected.png (RMS 16.765)

======================================================================
FAIL: SALib.tests.test_plotting.test_morris_covariance_plot_grouped.test
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/stijn_vanhoey/githubs/forks/SALib/.eggs/nose-1.3.7-py3.5.egg/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/stijn_vanhoey/miniconda2/envs/salibwill/lib/python3.5/site-packages/matplotlib/testing/decorators.py", line 53, in failer
    result = f(*args, **kwargs)
  File "/home/stijn_vanhoey/miniconda2/envs/salibwill/lib/python3.5/site-packages/matplotlib/testing/decorators.py", line 220, in do_test
    '(RMS %(rms).3f)'%err)
matplotlib.testing.exceptions.ImageComparisonFailure: images not close: /home/stijn_vanhoey/githubs/forks/SALib/result_images/test_plotting/covariance_plot_grouped.png vs. /home/stijn_vanhoey/githubs/forks/SALib/result_images/test_plotting/covariance_plot_grouped-expected.png (RMS 15.536)

----------------------------------------------------------------------
Ran 95 tests in 15.109s
```

I do understand that this is rather an matplotlib issue as it is a SAlib issue. However, I do think this should be tackled as potential contributors to the SAlib will ran to these issues in the future as well. Similar issues are reported, check [this entry](http://stackoverflow.com/questions/27948126/how-can-i-write-unit-tests-against-code-that-uses-matplotlib) from the seaborn author, proposing to not use these comparison on images directly, but rather adadpt the unit tests to compare the elments inside the graph CONTRIBUTING.md(`get_xydata()`). If that would be not feasible, make sure to inform potential contributors in the [](https://github.com/SALib/SALib/blob/master/CONTRIBUTING.md) file about this comparison failure.

**Comment by jdherman** [comment]
Thanks @willu47 and @stijnvanhoey. I don't think the data comparison will work here, since we're hardcoding it in the test. The point of the test is only to make sure the plotting code works. The recommendation of the link seems to be just to assume that the plot works, given the correct data -- if we make this assumption, should we remove these tests?

Another option might be to force the same backend. In `test_plotting.py` there is a commented-out line `matplotlib.use('agg')` should we uncomment that?

**Comment by willu47** [comment]
Given that this is not critical functionality for the library, I propose we skip these tests.  I'll submit a PR shortly.
