### ISSUE TITLE
Installation Failure: Command "python setup.py egg_info" failed with error code 1. 

### ISSUE THREAD

**Issue by ibaris** [SALib/SALib#182]
I tried to install SALib with ```pip install SALib``` (Command Prompt as an Administrator) but it failed on my system (Windows 10, Python 2.7.13 |Anaconda custom (64-bit)| [MSC v.1500 64 bit (AMD64)] on win32) with error code 1:

```
C:\WINDOWS\system32>pip install SALib
Collecting SALib
  Using cached SALib-1.1.2.tar.gz
    Complete output from command python setup.py egg_info:

    Installed c:\users\xxx\appdata\local\temp\pip-build-p0iccs\salib\.eggs\pyscaffold-2.5.8-py2.7.egg
    ERROR:root:Error parsing
    Traceback (most recent call last):
      File "c:\users\xxx\appdata\local\temp\pip-build-p0iccs\salib\.eggs\pyscaffold-2.5.8-py2.7.egg\pyscaffold\contrib\pbr\pbr\core.py", line 111, in pbr
        attrs = util.cfg_to_args(path, dist.script_args)
      File "c:\users\xxx\appdata\local\temp\pip-build-p0iccs\salib\.eggs\pyscaffold-2.5.8-py2.7.egg\pyscaffold\contrib\pbr\pbr\util.py", line 267, in cfg_to_args
        wrap_commands(kwargs)
      File "c:\users\xxx\appdata\local\temp\pip-build-p0iccs\salib\.eggs\pyscaffold-2.5.8-py2.7.egg\pyscaffold\contrib\pbr\pbr\util.py", line 569, in wrap_commands
        cmdclass = ep.resolve()
      File "C:\Users\xxx\Anaconda2\lib\site-packages\pkg_resources\__init__.py", line 2411, in resolve
        module = __import__(self.module_name, fromlist=['__name__'], level=0)
      File "C:\Users\xxx\Anaconda2\lib\site-packages\sphinx\setup_command.py", line 23, in <module>
        from sphinx.application import Sphinx
      File "C:\Users\xxx\Anaconda2\lib\site-packages\sphinx\application.py", line 33, in <module>
        from sphinx.environment import BuildEnvironment
      File "C:\Users\xxx\Anaconda2\lib\site-packages\sphinx\environment\__init__.py", line 45, in <module>
        from sphinx.util.websupport import is_commentable
      File "C:\Users\xxx\Anaconda2\lib\site-packages\sphinx\util\websupport.py", line 11, in <module>
        from sphinxcontrib.websupport.utils import is_commentable  # NOQA
      File "C:\Users\xxx\Anaconda2\lib\site-packages\sphinxcontrib\websupport\__init__.py", line 15, in <module>
        from sphinxcontrib.websupport.core import WebSupport  # NOQA
      File "C:\Users\xxx\Anaconda2\lib\site-packages\sphinxcontrib\websupport\core.py", line 17, in <module>
        from jinja2 import Environment, FileSystemLoader
      File "C:\Users\xxx\Anaconda2\lib\site-packages\jinja2\__init__.py", line 33, in <module>
        from jinja2.environment import Environment, Template
      File "C:\Users\xxx\Anaconda2\lib\site-packages\jinja2\environment.py", line 15, in <module>
        from jinja2 import nodes
      File "C:\Users\xxx\Anaconda2\lib\site-packages\jinja2\nodes.py", line 19, in <module>
        from jinja2.utils import Markup
      File "C:\Users\xxx\Anaconda2\lib\site-packages\jinja2\utils.py", line 486, in <module>
        MutableMapping.register(LRUCache)
      File "C:\Users\xxx\Anaconda2\lib\abc.py", line 109, in register
        if issubclass(subclass, cls):
      File "C:\Users\xxx\Anaconda2\lib\abc.py", line 180, in __subclasscheck__
        if issubclass(subclass, scls):
      File "C:\Users\xxx\Anaconda2\lib\site-packages\typing.py", line 1265, in __subclasscheck__
        return super(GenericMeta, self).__subclasscheck__(cls)
    TypeError: super() argument 1 must be type, not None
    error in setup command: Error parsing c:\users\xxx\appdata\local\temp\pip-build-p0iccs\SALib\setup.cfg: TypeError: super() argument 1 must be type, not None

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in c:\users\xxx\appdata\local\temp\pip-build-p0iccs\SALib\```

**Comment by jdherman** [comment]
Thanks for the bug report. This looks like it's way way down in the dependencies, and is possibly a Python 2 compatibility problem with one or more of them. I'm not sure there's much we can do on our side. In the meantime, you can always download the repo from github and use as a local module as in the examples.

(@willu47 do you see anything in here that we might do to fix the problem?)

**Comment by ibaris** [comment]
Thank you very much for your reply @jdherman . I will try to use it as a local module.

**Comment by knick007** [comment]
Fixed this with `sudo apt-get install pandoc`

**Comment by willu47** [comment]
Thanks for the hack @knick007 !  A new version of PyScaffold (v3.0) should fix these and other issues that are a result of this dependency, but unfortunately PyScaffold v3.0 isn't backwards compatible with Python 2.

**Comment by willu47** [comment]
SALib>=1.3 now uses Pyscaffold 3
