### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by ivan-marroquin** [SALib/SALib#197]
Hi,

I have a windows machine with conda 3.4 and Python 3.6.1 installed. When I ran the command: python setup.py install, I got this error:

(base) C:\Users\IMarroquin\Downloads\SALib-master>python setup.py install

Installed c:\users\imarroquin\downloads\salib-master\.eggs\pyscaffold-2.5.11-py3.6.egg
ERROR:root:Error parsing
Traceback (most recent call last):
  File "c:\users\imarroquin\downloads\salib-master\.eggs\pyscaffold-2.5.11-py3.6.egg\pyscaffold\contrib\pbr\pbr\core.py", line 96, in pbr
    attrs = util.cfg_to_args(path, dist.script_args)
  File "c:\users\imarroquin\downloads\salib-master\.eggs\pyscaffold-2.5.11-py3.6.egg\pyscaffold\contrib\pbr\pbr\util.py", line 258, in cfg_to_args
    pbr.hooks.setup_hook(config)
  File "c:\users\imarroquin\downloads\salib-master\.eggs\pyscaffold-2.5.11-py3.6.egg\pyscaffold\contrib\pbr\pbr\hooks\__init__.py", line 25, in setup_hook
    metadata_config.run()
  File "c:\users\imarroquin\downloads\salib-master\.eggs\pyscaffold-2.5.11-py3.6.egg\pyscaffold\contrib\pbr\pbr\hooks\base.py", line 27, in run
    self.hook()
  File "c:\users\imarroquin\downloads\salib-master\.eggs\pyscaffold-2.5.11-py3.6.egg\pyscaffold\contrib\pbr\pbr\hooks\metadata.py", line 26, in hook
    self.config['name'], self.config.get('version', None))
  File "c:\users\imarroquin\downloads\salib-master\.eggs\pyscaffold-2.5.11-py3.6.egg\pyscaffold\contrib\pbr\pbr\packaging.py", line 816, in get_version
    name=package_name))
Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. It's also possible that there is a mismatch between the package name in setup.cfg and
the argument given to pbr.version.VersionInfo. Project name SALib was given, but was not able to be found.
error in setup command: Error parsing C:\Users\IMarroquin\Downloads\SALib-master\setup.cfg: Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git reposi
tory. It's also possible that there is a mismatch between the package name in setup.cfg and the argument given to pbr.version.VersionInfo. Project name SALib was given, but was not able to be found.

Based on this message, I run the command "conda list" and noticed that I don't have pyscaffold installed. 

Do I need pyscaffold to install SALib? If so, can I download pyscaffold 3.0 which is compatible with Python 3.4?

Many thanks,
Ivan

**Comment by ivan-marroquin** [comment]
Thank you so much!
