### ISSUE TITLE
ImportError: cannot import name 'comb' while importing Morris sample and analyze

### ISSUE THREAD

**Issue by heavenlyhosts128** [SALib/SALib#245]
Hi! 

I updated to SALib 1.3.4 from 1.2. When I import the Morris sample or analyze, I get the following error:

>>> from SALib.sample.morris import sample
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/hossein/py3env/lib/python3.6/site-packages/SALib/sample/morris/__i             nit__.py", line 34, in <module>
    from . gurobi import GlobalOptimisation
  File "/home/hossein/py3env/lib/python3.6/site-packages/SALib/sample/morris/gur             obi.py", line 19, in <module>
    from scipy.misc import comb as nchoosek
ImportError: cannot import name 'comb'

Would you please help me with this?

**Comment by ConnectedSystems** [comment]
@willu47 and @jdherman my recent PR to the `develop` branch addresses this issue

**Comment by willu47** [comment]
Thanks, merged into master, release to follow shortly.
