### ISSUE TITLE
Unable to install v1.3.7 on Python 2.7

### ISSUE THREAD

**Issue by dxdc** [SALib/SALib#256]
Install of SALib-1.3.7 fails on Python 2.7. Based on a related discussion, I believe this would solve the issue, but not familiar enough with the library to ensure compatibility:

https://github.com/pbrod/numdifftools/issues/37#issuecomment-395794866

```log
Collecting salib
  Using cached https://files.pythonhosted.org/packages/12/8b/14f6c0f0a12b29d5e1766e7a585269cd6ec9728a63886c161a6eddb4e7fa/SALib-1.3.7.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/rv/spd1m5_524j35pnylts_bxvm0000gn/T/pip-install-w_1pbI/salib/setup.py", line 37, in <module>
        setup_package()
      File "/private/var/folders/rv/spd1m5_524j35pnylts_bxvm0000gn/T/pip-install-w_1pbI/salib/setup.py", line 33, in setup_package
        use_pyscaffold=True)
      File "/usr/local/lib/python2.7/site-packages/setuptools/__init__.py", line 144, in setup
        _install_setup_requires(attrs)
      File "/usr/local/lib/python2.7/site-packages/setuptools/__init__.py", line 139, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/usr/local/lib/python2.7/site-packages/setuptools/dist.py", line 717, in fetch_build_eggs
        replace_conflicting=True,
      File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 782, in resolve
        replace_conflicting=replace_conflicting
      File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1065, in best_match
        return self.obtain(req, installer)
      File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1077, in obtain
        return installer(requirement)
      File "/usr/local/lib/python2.7/site-packages/setuptools/dist.py", line 784, in fetch_build_egg
        return cmd.easy_install(req)
      File "/usr/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 679, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/usr/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 705, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/usr/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 890, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/usr/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1158, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/usr/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1144, in run_setup
        run_setup(setup_script, args)
      File "/usr/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 253, in run_setup
        raise
      File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 35, in __exit__
        self.gen.throw(type, value, traceback)
      File "/usr/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 35, in __exit__
        self.gen.throw(type, value, traceback)
      File "/usr/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 166, in save_modules
        saved_exc.resume()
      File "/usr/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 141, in resume
        six.reraise(type, exc, self._tb)
      File "/usr/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 154, in save_modules
        yield saved
      File "/usr/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/usr/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 250, in run_setup
        _execfile(setup_script, ns)
      File "/usr/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 45, in _execfile
        exec(code, globals, locals)
      File "/var/folders/rv/spd1m5_524j35pnylts_bxvm0000gn/T/easy_install-ozE0Ta/PyScaffold-3.0.3/setup.py", line 107, in <module>
    
      File "/var/folders/rv/spd1m5_524j35pnylts_bxvm0000gn/T/easy_install-ozE0Ta/PyScaffold-3.0.3/setup.py", line 102, in setup_package
    
      File "/var/folders/rv/spd1m5_524j35pnylts_bxvm0000gn/T/easy_install-ozE0Ta/PyScaffold-3.0.3/setup.py", line 76, in bootstrap_cfg
    
      File "/var/folders/rv/spd1m5_524j35pnylts_bxvm0000gn/T/easy_install-ozE0Ta/PyScaffold-3.0.3/src/pyscaffold/utils.py", line 274, in check_setuptools_version
    RuntimeError: Due to a bug in setuptools, PyScaffold currently needs at least Python 3.4! Install PyScaffold 2.5 for Python 2.7 support.
```

**Comment by ConnectedSystems** [comment]
Hi @dxdc 

As noted on the project page, SALib does not support Python 2 from v1.2 onwards.

Given that Py2.7 will reach end of life at the end of this year, could I encourage you to update?
(see links below for more information if you were not aware)

* https://www.anaconda.com/end-of-life-eol-for-python-2-7-is-coming-are-you-ready/
* https://legacy.python.org/dev/peps/pep-0373/

Alternatively you could try one of the older releases by adding the version number, like so:

```$ pip install salib==1.1.3 ```

**Comment by dxdc** [comment]
Thanks @ConnectedSystems  - understood, just thought this may be a viable fix (not sure what other features of Python 2.7 aren't supported).

**Comment by ConnectedSystems** [comment]
One other thing you could try - and I can't guarantee it will work - but if you have cloned the project you can modify the `setup.py` file as a possible work-around:

Line 32 or there abouts, change the following line:

```use_pyscaffold=True```

to 

```use_pyscaffold=False```

save, and then install the package under develop mode like so:

```python setup.py develop```

This _might_ work... again can't guarantee it will work 100% even if it installs

**Comment by ConnectedSystems** [comment]
Closing this issue for now, but feel free to reopen if you have any more questions.
