### ISSUE TITLE
conda release > 1.1.2

### ISSUE THREAD

**Issue by revesansparole** [SALib/SALib#271]
It seems that the latest versions of SALib are only available on PyPI. Our workflow requires conda so I had to package it on our 'personal' channel. I'll be happy to contribute and deploy it on conda-forge for you instead.

**Comment by willu47** [comment]
Hi @revesansparole - we already have a conda-forge feedstock. I also noted that this has not be updated recently. Would you like to become a maintainer for the feedstock?

**Comment by revesansparole** [comment]
Would you prefer I'll do it by hand or shall I modify your travis.ci to publish it on your conda-forge channel alongside deployment on pypi?

**Comment by willu47** [comment]
Hi @revesansparole - SALib is available on conda-forge - https://github.com/conda-forge/salib-feedstock

I think all that needs to be done is for the branches to be merged in after the tests are passing

**Comment by revesansparole** [comment]
miss that one, I'll create a PR to trigger the new version as soon as possible

**Comment by jdherman** [comment]
I see @willu47 is working on a PR for this:
https://github.com/conda-forge/salib-feedstock/pull/15

The error is `no module named pip`, but during the build it looks like there are about 3 different pips floating around (3.7, 3.8, and maybe 2.7 ??) That could be part of the issue.

But after that's resolved I don't think we need to change anything else. It would be great if we could have a person who can keep this updated. I'd be happy to do it whenever the bot submits a PR, but if there are issues like this one I won't know how to fix it.

**Comment by revesansparole** [comment]
I'm way above my head here and I'm not sure I understand everything that is done automatically but when I run the recipe locally I seem to have an error related to the setup.py generated in salib by pyscaffold:

Traceback (most recent call last):
  File "setup.py", line 23, in <module>
    setup_package()
  File "setup.py", line 19, in setup_package
    use_pyscaffold=True)
  File "C:\Users\jchopard\AppData\Local\Continuum\miniconda3\envs\pkg\conda-bld\salib_1573237864013\_h_env\lib\site-packages\setuptools\__init__.py", line 144, in setup
    _install_setup_requires(attrs)
  File "C:\Users\jchopard\AppData\Local\Continuum\miniconda3\envs\pkg\conda-bld\salib_1573237864013\_h_env\lib\site-packages\setuptools\__init__.py", line 139, in _install_setup_requires
    dist.fetch_build_eggs(dist.setup_requires)
  File "C:\Users\jchopard\AppData\Local\Continuum\miniconda3\envs\pkg\conda-bld\salib_1573237864013\_h_env\lib\site-packages\setuptools\dist.py", line 720, in fetch_build_eggs
    replace_conflicting=True,
  File "C:\Users\jchopard\AppData\Local\Continuum\miniconda3\envs\pkg\conda-bld\salib_1573237864013\_h_env\lib\site-packages\pkg_resources\__init__.py", line 782, in resolve
    replace_conflicting=replace_conflicting
  File "C:\Users\jchopard\AppData\Local\Continuum\miniconda3\envs\pkg\conda-bld\salib_1573237864013\_h_env\lib\site-packages\pkg_resources\__init__.py", line 1065, in best_match
    return self.obtain(req, installer)
  File "C:\Users\jchopard\AppData\Local\Continuum\miniconda3\envs\pkg\conda-bld\salib_1573237864013\_h_env\lib\site-packages\pkg_resources\__init__.py", line 1077, in obtain
    return installer(requirement)
  File "C:\Users\jchopard\AppData\Local\Continuum\miniconda3\envs\pkg\conda-bld\salib_1573237864013\_h_env\lib\site-packages\setuptools\dist.py", line 787, in fetch_build_egg
    return cmd.easy_install(req)
  File "C:\Users\jchopard\AppData\Local\Continuum\miniconda3\envs\pkg\conda-bld\salib_1573237864013\_h_env\lib\site-packages\setuptools\command\easy_install.py", line 667, in easy_install
    not self.always_copy, self.local_index
  File "C:\Users\jchopard\AppData\Local\Continuum\miniconda3\envs\pkg\conda-bld\salib_1573237864013\_h_env\lib\site-packages\setuptools\package_index.py", line 658, in fetch_distribution
    self.find_packages(requirement)
  File "C:\Users\jchopard\AppData\Local\Continuum\miniconda3\envs\pkg\conda-bld\salib_1573237864013\_h_env\lib\site-packages\setuptools\package_index.py", line 491, in find_packages
    self.scan_url(self.index_url + requirement.unsafe_name + '/')
  File "C:\Users\jchopard\AppData\Local\Continuum\miniconda3\envs\pkg\conda-bld\salib_1573237864013\_h_env\lib\site-packages\setuptools\package_index.py", line 831, in scan_url
    self.process_url(url, True)
  File "C:\Users\jchopard\AppData\Local\Continuum\miniconda3\envs\pkg\conda-bld\salib_1573237864013\_h_env\lib\site-packages\setuptools\package_index.py", line 326, in process_url
    "Be sure to add all dependencies in the meta.yaml  url=%s" % url)
RuntimeError: Setuptools downloading is disabled in conda build. Be sure to add all dependencies in the meta.yaml  url=https://pypi.org/simple/pyscaffold/

**Comment by jdherman** [comment]
This is over my head for sure, thanks for working on it. The error on the system build happens when running the docker shell script:
```
...
Success
Extracting download
source tree in: /home/conda/feedstock_root/build_artifacts/salib_1573136630595/work
export PREFIX=/home/conda/feedstock_root/build_artifacts/salib_1573136630595/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place
export BUILD_PREFIX=/home/conda/feedstock_root/build_artifacts/salib_1573136630595/_build_env
export SRC_DIR=/home/conda/feedstock_root/build_artifacts/salib_1573136630595/work
/home/conda/feedstock_root/build_artifacts/salib_1573136630595/_build_env/bin/python: No module named pip
```
full output here:
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=90809

I wasn't able to get it running locally, but that error about setuptools didn't show up anywhere in the log. But maybe we also have that to look forward to at some point.

**Comment by ConnectedSystems** [comment]
@willu47 @jdherman 

I believe this issue has now been resolved, but please reopen if there are other related issues lingering on.
