### ISSUE TITLE
Bug in enhanced_hdmr max_order=1

### ISSUE THREAD

**Issue by willu47** [SALib/SALib#642]
When running `morris.analyze.enhanced_hdmr` with `max_order=1`, an error is raised.

```python
Traceback (most recent call last):
  File "/Users/wusher_1/repository/SALib/tests/test_enhanced_hdmr.py", line 53, in <module>
    Si = enhanced_hdmr.analyze(problem, X, Y, **options)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/wusher_1/repository/SALib/src/SALib/analyze/enhanced_hdmr.py", line 232, in analyze
    Si = _finalize(hdmr, Si, alpha, return_emulator)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/wusher_1/repository/SALib/src/SALib/analyze/enhanced_hdmr.py", line 1439, in _finalize
    TS = hdmr.S[r, :]
         ^^^^^^
AttributeError: 'CoreParams' object has no attribute 'S'
```

The following code reproduces the error as seen in SALib `v1.4.7`:

```python

import numpy as np
from SALib.analyze import enhanced_hdmr
from SALib.sample import latin

# Create a problem dictionary
problem = {
    "num_vars": 12,
    "names": [
        "PA|Agriculture|Kc",
        "PA|Agriculture|Soil Water Capacity",
        "PA|Agriculture|Root Zone Conductivity",
        "PA|Agriculture|Runoff Resistance Factor",
        "PA|Forest|Kc",
        "PA|Forest|Soil Water Capacity",
        "PA|Forest|Root Zone Conductivity",
        "PA|Forest|Runoff Resistance Factor",
        "PA|Grassland|Kc",
        "PA|Grassland|Soil Water Capacity",
        "PA|Grassland|Root Zone Conductivity",
        "PA|Grassland|Runoff Resistance Factor",
    ],
    "bounds": [
        [0.8, 1.4],
        [300, 600],
        [2, 8],
        [.05, .5],
        [.2, .4],
        [150, 900],
        [2, 5],
        [.5, 1.5],
        [.6, 1.3],
        [250, 600],
        [3, 7],
        [0.1, 1.2]
    ]
}

X = latin.sample(problem, 1000, seed=101)

# Run the model to obtain Y (using randomly generated values)
rng = np.random.default_rng()
Y = rng.standard_normal(1000)

# SALib-HDMR options
options = {
    "max_order": 1,
    "max_iter": 100,
    "alpha": 0.95,
    "print_to_console": True,
    "seed": 101,
}
# Run SALib-HDMR
Si = enhanced_hdmr.analyze(problem, X, Y, **options)
```

**Comment by willu47** [comment]
I also noticed that the interface (arguments) to hdmr and enhanced_hdmr are different, which makes it difficult to migrate from hdmr to enhanced_hdmr.
