### ISSUE TITLE
SALib IndexError for FAST with low number of samples

### ISSUE THREAD

**Issue by ms314** [SALib/SALib#99]
Hi,

FAST behaves strangely when a low number of samples is used. I run the Ishigami example model function by using the script

```python
from SALib.sample import fast_sampler
from SALib.analyze import fast
from SALib.test_functions import Ishigami

problem = {
    'num_vars': 3,
    'names': ['x1', 'x2', 'x3'],
    'bounds': [[-3.14159265359, 3.14159265359],
               [-3.14159265359, 3.14159265359],
               [-3.14159265359, 3.14159265359]]
}

param_values = fast_sampler.sample(problem, 33)

Y = Ishigami.evaluate(param_values)

Si = fast.analyze(problem, Y, print_to_console=False)
```
Using more than 33 samples (tested with > 70) runs perfectly fine. However, using this (33) or lower sample values results in the following error:
```
SALib\sample\fast_sampler.py:39: RuntimeWarning: invalid value encountered in remainder
  omega[1:] = np.arange(D - 1) % m + 1
\SALib\analyze\fast.py:70: RuntimeWarning: invalid value encountered in remainder
  omega[1:] = np.arange(D - 1) % m + 1
\SALib\analyze\fast.py:88: RuntimeWarning: invalid value encountered in power
  Sp = np.power(np.absolute(f[np.arange(1, int(N / 2))]) / N, 2)
Traceback (most recent call last):
  File "test.py", line 17, in <module>
    Si = fast.analyze(problem, Y, print_to_console=False)
  File "SALib\analyze\fast.py", line 78, in analyze
    Si['S1'][i] = compute_first_order(Y[l], N, M, omega[0])
  File "SALib\analyze\fast.py", line 90, in compute_first_order
    D1 = 2 * np.sum(Sp[np.arange(1, M + 1) * int(omega) - 1])
IndexError: index 15 is out of bounds for axis 0 with size 15
```
Although such a low sampling number is rarely needed in practice, it would be good to have an automatic check / warning if the number of samples is too low in case this error should be related to accuracy reasons in the FAST approach.

**Comment by jdherman** [comment]
Thanks @ms314 ... the sample size has to be N > 4M^2, or else all kinds of strange errors might happen. In PR #100 I added an error message to catch this.
